config/routes.rb
Rails.application.routes.draw do
  
  namespace 'api' do
    namespace 'v1' do
      resources :users
      resources :historylogs
      resources :triptransactions
      resources :historyloads
      resources :balanceloads
    end
  end
  post   'session', to: 'session#create', as: 'login'
  delete 'session', to: 'session#destroy', as: 'logout'

  get 'users/index'
  get 'users/users'
  get 'users/trip_transactions'
  get 'users/balance_loads'
  get 'users/history_loads'
resources :users
root 'users#login'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :trip_transaction
  has_many :history_load
  has_secure_password
  has_secure_token :auth_token
  validates_uniqueness_of :email

  # validates :last_name, presence: true
  # validates :first_name, presence: true
  # validates :middle_name, presence: true
  # validates :email, presence: true
  validates :password, presence: true, :on => :create
  # validates :mobile_number, presence: true
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController

  def index
    users = User.order('created_at DESC');
    render json: users.reload, status: :ok
  end

  def create
    user = User.new(users_params)
    if user.save
      render json: user.reload, status: :ok
    else
      render json: user.errors, status: :bad_request
    end
  end

  def update
    user = User.find(params[:id])
    if user.update_attributes(users_params)
      render json: user.reload, status: :ok
    else
      render json: user.errors, status: :bad_request
    end
  end

  private

  def users_params
    params.permit(:last_name, :first_name, :middle_name, :email, :password, :password_confirmation, :mobile_number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def users
  	@users=User.all
  end

  def trip_transactions
  end

  def balance_loads
  end

  def history_loads
  end

  def index
  	
  end
end

app/views/users/balance_loads.html.erb
<h1>Users#balance_loads</h1>
<p>Find me in app/views/users/balance_loads.html.erb</p>

app/views/users/history_loads.html.erb
<h1>Users#history_loads</h1>
<p>Find me in app/views/users/history_loads.html.erb</p>

app/views/users/index.html.erb
<body>
    <%= link_to "Users", users_users_path%>
    <%= link_to "Trip Transactions", users_trip_transactions_path%>
    <%= link_to "Balance Loads", users_balance_loads_path%>
    <%= link_to "History Loads", users_history_loads_path%>
 	<%= link_to "Logout", root_path%>
    <%= yield %>
  </body>

app/views/users/login.html.erb
<div class = "login">
	<p>PLEASE LOG IN </p>
      <form action = "signin">
          <input type= "text" placeholder = "username" name = "username"></br>
          <input type = "password" placeholder = "password" name = "pass"> <br>
          <%= link_to '<button type = "button"> LOGIN </button>'.html_safe, users_index_path%>
       </form>
    
  </div>

app/views/users/trip_transactions.html.erb
<h1>Users#trip_transactions</h1>
<p>Find me in app/views/users/trip_transactions.html.erb</p>

app/views/users/users.html.erb
<div class="users_t">
    <table>
          
      <tr>
        <th>User ID</th>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Middle Name</th>
        <th>Email</th>
        <th>Mobile Number</th>
      </tr>

      <% @users.each do |user| %>
      <tr>
          <td> <%= user.id %> </td>
          <td> <%= user.last_name %> </td>
          <td> <%= user.first_name %> </td>
          <td> <%= user.middle_name %> </td>
          <td> <%= user.email %> </td>
          <td> <%= user.mobile_number %> </td>
      </tr>
      <% end %>

    </table>
</div>